# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j1:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  j2:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  j3:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  j4:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  j5:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
  j6:
    has_position_limits: true
    max_position: 3.14
    min_position: 0
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 1
