# Simulation settings for using moveit_sim_controllers
controller_list:
  - name: "/controllers/position"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
